
def create(name,path):
	file= open(path+".urdf","w")
	file.write("<?xml version='1.0' ?>\n")
	file.write("<robot name='"+name+"'>\n")
	file.write("  <link name='"+name+"Link'>\n")
	file.write("  <contact>\n")
	file.write("      <lateral_friction value='1'/>\n")
	file.write("  </contact>\n")
	file.write("    <inertial>\n")
	file.write("      <origin rpy='0 0 0' xyz='0 0 0'/>\n")
	file.write("       <mass value='.0'/>\n")
	file.write("       <inertia ixx='0' ixy='0' ixz='0' iyy='0' iyz='0' izz='0'/>\n")
	file.write("    </inertial>\n")
	file.write("    <visual>\n")
	file.write("      <origin rpy='0 0 0' xyz='0 0 0'/>\n")
	file.write("      <geometry>\n")
	file.write("		<mesh filename='"+name+".obj' scale='1 1 1'/>\n")
	file.write("      </geometry>\n")
	file.write("    </visual>\n")
	file.write("    <collision>\n")
	file.write("      <origin rpy='0 0 0' xyz='0 0 -5'/>\n")
	file.write("      <geometry>\n")
	file.write("	 	<box size='1 1 1'/>\n")
	file.write("      </geometry>\n")
	file.write("    </collision>\n")
	file.write("  </link>\n</robot>")
	file.close()

